### ISSUE TITLE
Module1:Peer to peer review

### ISSUE THREAD

**Issue by svitalis123** [Balikuddembe/Personal-Portfolio#12]
Excellent work 👏 🥇 

## Highlights
- Good GitHub flow
- Excellent use of HTML5 Tags.
- Excellent code flow

## Required Changes.
Please replace wrappers of `img` as `a` tag to Wrap them in `div`. For better semantic.

Happy coding 🗼 🥂

**Comment by Balikuddembe** [comment]
Thank you @svitalis123 for the suggestion and good feedback 😄 
- I am going to implement the raised issue 💯
