### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by SaboorSohaib** [Balikuddembe/Personal-Portfolio#9]
# Hi @Balikuddembe 👋 

- You did a great job.
- Your code was clean and dry.

Kindly I will suggest you something if you do ut it will be better and you will get more dry code
- kindly remove the label from the form so it will match figma's design.

**Comment by Balikuddembe** [comment]
Thank you @SaboorSohaib for the issue raised.I am going to fix the issue as suggested.
Cheers and happy coding team
